# Site-wide settings
title: Abhishek Ranjan
author:
  name: abhishekrp2002
  email: aviranjan444@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  personal brain dump of an ml engineer passionate about solving real-world problems, 
  where he shares his insights, experiments, annotations, and lessons learned.
  decoding the future, one algorithm at a time!

# Build settings
# --------------
# If you wish to use the gem-version of Minima with or without a Gemfile:
theme: minima

# **OR** use the theme directly from GitHub (latest features):
# remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Uncomment to disable deprecation warnings from newer versions of sass converter
sass:
  quiet_deps: true
  silence_deprecations: [import]


# Minima-specific settings (applicable to Minima v3 and above only)
minima:
  # Available skins: classic, dark, auto, solarized-light, solarized-dark, solarized
  skin: auto  # Adaptive skin based on user's system preference

  # Specific pages for site navigation
  nav_pages:
    - about.md

  # Set to `true` to show excerpts on the homepage
  show_excerpts: true

  # Minima date format (default: "%b %d, %Y")
  date_format: "%b %d, %Y"

  # Social Media Links (rendered via Font Awesome icons)
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/AbhishekRP2002"
    - title: LinkedIn
      icon: linkedin
      url: "https://linkedin.com/in/abhishekrp2002"
    - title: X (Twitter)
      icon: x-twitter
      url: "https://x.com/abhishekrp2002"

  # Hide syndication feed subscription link (set to true to hide)
  # hide_site_feed_link: false
